name: Release Helm Chart

on:
  push:
    tags:
      - 'chart-v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Lint Helm chart
        run: |
          helm lint deploy/helm/asciinema-server-x

      - name: Install yq
        run: |
          YQ_VERSION=v4.44.3
          curl -L -o yq https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64
          sudo install -m 0755 yq /usr/local/bin/yq

      - name: Package Helm chart
        run: |
          helm package deploy/helm/asciinema-server-x --destination .

      - name: Log in to GHCR for Helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Helm chart to GHCR (OCI)
        run: |
          CHART_NAME=$(yq '.name' deploy/helm/asciinema-server-x/Chart.yaml)
          CHART_VERSION=$(yq '.version' deploy/helm/asciinema-server-x/Chart.yaml)
          CHART_REPO=oci://ghcr.io/${{ github.repository_owner }}
          helm push ${CHART_NAME}-${CHART_VERSION}.tgz ${CHART_REPO}

